<a href="https://colab.research.google.com/github/Carmen-GL/repo_master_/blob/main/01_PyTorch_Basico_Ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![IDAL](https://i.imgur.com/tIKXIG1.jpg)  

#**Máster en Inteligencia Artificial Avanzada y Aplicada:  IA^3**
---


# PyTorch Basico Ejercicios 

En estos ejercicos crearemos algunos tensores y realizaremos operaciones básicos sobre ellos.


### 1. Realiza las importaciones standard
Importa torch and NumPy

In [ ]:
# TU CÓDIGO AQUÍ
import torch
import numpy as np

### 2. Configura una semilla para los generadores de ambos Numpy y Pytorch con el valor "42"
Esto permite reproducir los mismos resultados "aleatorios"

In [ ]:
# TU CÓDIGO AQUÍ
torch.manual_seed(42)
np.random.seed(42)

### 3. Crea un NumPy array llamado "arr" que contenga 6 enteros aleatorios entre 0 (incluido) y 5 (excluido)

In [ ]:
# TU CÓDIGO AQUÍ
arr = np.random.randint(0,5,6)
print(arr)

[3 4 2 4 4 1]


In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

[3 4 2 4 4 1]


### 4. Crea a tensor "x" del array anterior 

In [ ]:
# TU CÓDIGO AQUÍ
x = torch.from_numpy(arr)
print(x)


tensor([3, 4, 2, 4, 4, 1])


In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([3, 4, 2, 4, 4, 1])


### 5. Cambia el tipo de dato (`dtype`) de x de 'int32' a 'int64'
Nota: 'int64' tambien se puede llamar 'LongTensor'

In [ ]:
# TU CÓDIGO AQUÍ
print(x.type())

x=x.type(torch.int32)
print(x.type())

torch.LongTensor
torch.IntTensor


In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

torch.LongTensor


### 6. Cambia la forma del tensor a un 3x2 tensor
Hay varias formas de hacer esto

In [ ]:
# TU CÓDIGO AQUÍ. También con reshape, resize
x=x.view(3,2)
#x.resize_(3,2) Son equivalentes
print(x)


tensor([[3, 4],
        [2, 4],
        [4, 1]], dtype=torch.int32)


In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Retorna la columna de la derecha del tensor x

Atención a la forma de hacerlo. Hay varias posibilidades y cada una entrega los datos de forma diferente

In [ ]:
# # TU CÓDIGO AQUÍ

print(x[:,1:])

tensor([[4],
        [4],
        [1]], dtype=torch.int32)


In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([[4],
        [4],
        [1]])


In [ ]:
# TU CÓDIGO AQUÍ
print (x[:,1])

tensor([4, 4, 1])


In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([4, 4, 1])


### 8. Sin cambiar x, retorna un tensor con los valores cuadradaticos de x
Hay varias formas de hacer esto

In [ ]:
# TU CÓDIGO AQUÍ

print(x*x)
print(x**2)
print(x.mul(x))
print(x.pow(2))
print(torch.mul(x,x))

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]], dtype=torch.int32)
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]], dtype=torch.int32)
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]], dtype=torch.int32)
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]], dtype=torch.int32)
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]], dtype=torch.int32)


In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Crea un tensor "y" con el mismo número de elementos que x, de forma que pueda realizar una multiplicación de matrices.

Utiliza funciones de Pytorch directamente para crear un tensor de enteros aleatorios entre 0 (incluido) y 5 (excluido). 

Ten en cuenta qué forma debe tener para hacer la multiplicación de matrices...

In [ ]:
# TU CÓDIGO AQUÍ
y=torch.randint(0,5,(2,3))
print(y)


tensor([[2, 2, 1],
        [4, 1, 0]])


In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Realiza el producto de matrices entre x e y

In [ ]:
# TU CÓDIGO AQUÍ
x= x.type(torch.int64)
print(x.mm(y))


tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


In [ ]:
# No escribas aquí. Compara tu resultado con lo que se muestra:

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Enhorabuena! Vamos calentando motores...

## Fin del Notebook

Referencias y modelos empleados para el Notebook: 

*   Documentación de [Pytorch](https://pytorch.org/docs/stable/index.html) 
*   [PyTorch Tutorial for Deep Learning Researchers](https://github.com/yunjey/pytorch-tutorial) by Yunjey Choi
*   [FastAI](https://www.fast.ai/) development notebooks by Jeremy Howard.
*   Documentación y cursos en [Pierian Data](https://www.pieriandata.com/)
