<a href="https://colab.research.google.com/github/Carmen-GL/repo_master_/blob/main/Pytorch_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aprendizaje profundo II

In [2]:
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [15]:
input_1d = torch.tensor([1,2,3,4,5,6,7,8,9,10], dtype = torch.float)

input_2d = torch.tensor ([[1,2,3,4,5], [6,7,8,9,10]], dtype = torch.float)

input_2d_img = torch.tensor([[[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]],[[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]],[[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]]], dtype = torch.float)

In [4]:
input_1d = input_1d.unsqueeze(0).unsqueeze(0)
input_1d.shape

torch.Size([1, 1, 10])

In [5]:
cnn1d_1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=1)

print("cnn1d_1: \n")
print(cnn1d_1(input_1d).shape, "\n")
print(cnn1d_1(input_1d))

cnn1d_1: 

torch.Size([1, 1, 8]) 

tensor([[[1.5256, 1.6807, 1.8358, 1.9908, 2.1459, 2.3009, 2.4560, 2.6111]]],
       grad_fn=<SqueezeBackward1>)


In [6]:
input_2d = input_2d.unsqueeze(0)
input_2d.shape

torch.Size([1, 2, 5])

In [7]:
cnn1d_5 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=1)

print("cnn1d_5: \n")
print(cnn1d_5(input_2d).shape, "\n")
print(cnn1d_5(input_2d))

cnn1d_5: 

torch.Size([1, 1, 3]) 

tensor([[[-1.3460, -1.4862, -1.6263]]], grad_fn=<SqueezeBackward1>)


In [8]:
cnn1d_6 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=2)

print("cnn1d_6: \n")
print(cnn1d_6(input_2d).shape, "\n")
print(cnn1d_6(input_2d))

cnn1d_6: 

torch.Size([1, 1, 2]) 

tensor([[[1.1327, 1.1349]]], grad_fn=<SqueezeBackward1>)


In [9]:
cnn1d_7 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=2, stride=1)

print("cnn1d_7: \n")
print(cnn1d_7(input_2d).shape, "\n")
print(cnn1d_7(input_2d))

cnn1d_7: 

torch.Size([1, 1, 4]) 

tensor([[[-1.1569, -1.4933, -1.8297, -2.1662]]], grad_fn=<SqueezeBackward1>)


In [10]:
cnn1d_8 = nn.Conv1d(in_channels=2, out_channels=5, kernel_size=3, stride=1)

print("cnn1d_8: \n")
print(cnn1d_8(input_2d).shape, "\n")
print(cnn1d_8(input_2d))

cnn1d_8: 

torch.Size([1, 5, 3]) 

tensor([[[ 2.8810,  3.7291,  4.5772],
         [ 1.3156,  1.9608,  2.6060],
         [ 1.4221,  1.3815,  1.3409],
         [-1.2869, -1.9070, -2.5270],
         [-6.3529, -6.7652, -7.1776]]], grad_fn=<SqueezeBackward1>)


In [11]:
cnn1d_9 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=1, padding=1)

print("cnn1d_9: \n")
print(cnn1d_9(input_2d).shape, "\n")
print(cnn1d_9(input_2d))

cnn1d_9: 

torch.Size([1, 1, 5]) 

tensor([[[-1.7969, -2.1531, -2.7992, -3.4452, -1.5824]]],
       grad_fn=<SqueezeBackward1>)


CONVOLUCIONES 2D

In [16]:
input_2d_img = input_2d_img.unsqueeze(0)
input_2d_img.shape

torch.Size([1, 3, 3, 10])

Cambiar stride

In [20]:
cnn2d_2 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, stride=2)

print("cnn2d_2: \n")
print(cnn2d_2(input_2d_img).shape, "\n")
print(cnn2d_2(input_2d_img))

cnn2d_2: 

torch.Size([1, 1, 1, 4]) 

tensor([[[[-0.0667, -0.3332, -0.5997, -0.8662]]]],
       grad_fn=<ThnnConv2DBackward0>)


Cambiar kernel size

In [22]:
cnn2d_3 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=2, stride=1)

print("cnn2d_3: \n")
print(cnn2d_3(input_2d_img).shape, "\n")
print(cnn2d_3(input_2d_img))

cnn2d_3: 

torch.Size([1, 1, 2, 9]) 

tensor([[[[-1.1044, -1.8842, -2.6640, -3.4438, -4.2236, -5.0033, -5.7831,
           -6.5629, -7.3427],
          [-1.1044, -1.8842, -2.6640, -3.4438, -4.2236, -5.0033, -5.7831,
           -6.5629, -7.3427]]]], grad_fn=<ThnnConv2DBackward0>)


Cambiar out_channels

In [23]:
cnn2d_4 = nn.Conv2d(in_channels=3, out_channels=5, kernel_size=3, stride=1)

print("cnn2d_4: \n")
print(cnn2d_4(input_2d_img).shape, "\n")
print(cnn2d_4(input_2d_img))

cnn2d_4: 

torch.Size([1, 5, 1, 8]) 

tensor([[[[ 2.5573,  3.8537,  5.1501,  6.4465,  7.7430,  9.0394, 10.3358,
           11.6322]],

         [[ 0.8796,  1.5493,  2.2190,  2.8887,  3.5584,  4.2281,  4.8978,
            5.5675]],

         [[-0.5115, -0.9352, -1.3589, -1.7826, -2.2063, -2.6300, -3.0538,
           -3.4775]],

         [[ 1.1027,  1.5288,  1.9549,  2.3811,  2.8072,  3.2333,  3.6594,
            4.0855]],

         [[ 1.0794,  1.5667,  2.0540,  2.5413,  3.0286,  3.5160,  4.0033,
            4.4906]]]], grad_fn=<ThnnConv2DBackward0>)


Añadir padding

In [25]:
cnn2d_5 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, stride=1, padding=1)

print("cnn2d_5: \n")
print(cnn2d_5(input_2d_img).shape, "\n")
print(cnn2d_5(input_2d_img))

cnn2d_5: 

torch.Size([1, 1, 3, 10]) 

tensor([[[[-0.1099, -0.1018, -0.0937, -0.0856, -0.0776, -0.0695, -0.0614,
           -0.0533, -0.0452,  0.0311],
          [ 0.0751,  0.2347,  0.3944,  0.5541,  0.7137,  0.8734,  1.0331,
            1.1928,  1.3524,  2.4368],
          [-0.1212, -0.1070, -0.0929, -0.0788, -0.0646, -0.0505, -0.0363,
           -0.0222, -0.0080,  2.8160]]]], grad_fn=<ThnnConv2DBackward0>)
